# ============================================================================
# SUPPLEMENTARY FIGURE S2 — PCA Variance Explained (REAL DATA)
# ============================================================================
# Data source: pca_explained_variance.csv
#   Columns: PC, explained_variance_ratio, cumulative_variance
#   Generated by: export_data_for_python.R (from real Seurat RunPCA output)
#   50 rows — one per PC — all real values from training set (37,883 cells)
# ============================================================================

library(ggplot2)
library(patchwork)

# ---- Paths ---------------------------------------------------------------
base_dir   <- getwd()   # run from the repository root
input_file <- file.path(base_dir, "pca_explained_variance.csv")
output_dir <- file.path(base_dir, "PublicationsFigure")
manuscript_dir <- file.path(base_dir, "manuscript", "generic_latex", "figures")

# ---- Confirm file exists -------------------------------------------------
if (!file.exists(input_file)) {
  stop(paste("ERROR: File not found:", input_file,
             "\nThis file must be generated by running export_data_for_python.R first."))
}

cat("Loading real PCA variance from:", input_file, "\n")

# ---- Load real data ------------------------------------------------------
pca_data <- read.csv(input_file, stringsAsFactors = FALSE)

# Confirm expected columns
expected_cols <- c("PC", "explained_variance_ratio", "cumulative_variance")
missing_cols  <- setdiff(expected_cols, colnames(pca_data))
if (length(missing_cols) > 0) {
  stop(paste("ERROR: Missing columns in pca_explained_variance.csv:",
             paste(missing_cols, collapse = ", ")))
}

# Convert to numeric PC index (strip "PC_" prefix if present)
pca_data$pc_num <- as.integer(gsub("PC_", "", pca_data$PC))

# Convert ratios to percentages
pca_data$variance_pct    <- pca_data$explained_variance_ratio * 100
pca_data$cumulative_pct  <- pca_data$cumulative_variance * 100

n_pcs <- nrow(pca_data)
cat(sprintf("Loaded %d PCs\n", n_pcs))
cat(sprintf("PC1:  %.2f%%  PC2: %.2f%%  PC3: %.2f%%\n",
            pca_data$variance_pct[1],
            pca_data$variance_pct[2],
            pca_data$variance_pct[3]))
cat(sprintf("Cumulative variance at PC50: %.1f%%\n",
            pca_data$cumulative_pct[n_pcs]))

# Find PC where cumulative variance first exceeds 80% and 90%
pc_80 <- pca_data$pc_num[which(pca_data$cumulative_pct >= 80)[1]]
pc_90 <- pca_data$pc_num[which(pca_data$cumulative_pct >= 90)[1]]
cat(sprintf("PC reaching 80%% cumulative variance: PC%d\n", pc_80))
cat(sprintf("PC reaching 90%% cumulative variance: PC%d\n", pc_90))

# ---- Publication theme ---------------------------------------------------
theme_pub <- theme_classic() +
  theme(
    axis.text        = element_text(size = 11, color = "black"),
    axis.title       = element_text(size = 13, face = "bold"),
    plot.title       = element_text(size = 14, face = "bold", hjust = 0.5),
    panel.grid.major = element_line(color = "grey92"),
    panel.grid.minor = element_blank()
  )

# ---- Panel A: Individual PC Variance (Elbow Plot) -----------------------
p_elbow <- ggplot(pca_data, aes(x = pc_num, y = variance_pct)) +
  geom_line(color = "#2c3e50", linewidth = 0.8) +
  geom_point(size = 2.5, color = "#2c3e50") +
  geom_vline(xintercept = 50, linetype = "dashed",
             color = "#e74c3c", linewidth = 0.9) +
  annotate("text", x = 47, y = max(pca_data$variance_pct) * 0.88,
           label = "50 PCs\nselected",
           hjust = 1, color = "#e74c3c", fontface = "bold", size = 3.5) +
  scale_x_continuous(breaks = seq(0, 50, 10), limits = c(1, 50)) +
  scale_y_continuous(labels = function(x) paste0(round(x, 1), "%")) +
  labs(x = "Principal Component",
       y = "Variance Explained (%)",
       title = "A. Variance per PC") +
  theme_pub

# ---- Panel B: Cumulative Variance ----------------------------------------
p_cumul <- ggplot(pca_data, aes(x = pc_num, y = cumulative_pct)) +
  geom_line(color = "#27ae60", linewidth = 0.8) +
  geom_point(size = 2.5, color = "#27ae60") +
  geom_hline(yintercept = 80, linetype = "dashed",
             color = "#f39c12", linewidth = 0.8) +
  geom_hline(yintercept = 90, linetype = "dashed",
             color = "#3498db", linewidth = 0.8) +
  geom_vline(xintercept = 50, linetype = "dashed",
             color = "#e74c3c", linewidth = 0.9) +
  annotate("text", x = 1, y = 82,
           label = paste0("80% at PC", pc_80),
           hjust = 0, color = "#f39c12", fontface = "bold", size = 3.2) +
  annotate("text", x = 1, y = 92,
           label = paste0("90% at PC", pc_90),
           hjust = 0, color = "#3498db", fontface = "bold", size = 3.2) +
  scale_x_continuous(breaks = seq(0, 50, 10), limits = c(1, 50)) +
  scale_y_continuous(limits = c(0, 100),
                     labels = function(x) paste0(x, "%")) +
  labs(x = "Principal Component",
       y = "Cumulative Variance (%)",
       title = "B. Cumulative Variance") +
  theme_pub

# ---- Combine panels ------------------------------------------------------
fig_s2 <- p_elbow + p_cumul +
  plot_annotation(
    title    = "Supplementary Figure S2: PCA Variance Explained",
    subtitle = sprintf(
      "50 PCs selected from 3,000 HVGs on %s training cells | PC1=%.1f%%, PC2=%.1f%%, Cumulative@PC50=%.1f%%",
      "37,883",
      pca_data$variance_pct[1],
      pca_data$variance_pct[2],
      pca_data$cumulative_pct[50]
    ),
    theme = theme(
      plot.title    = element_text(size = 16, face = "bold", hjust = 0.5),
      plot.subtitle = element_text(size = 10, hjust = 0.5, color = "grey40")
    )
  )

# ---- Save ---------------------------------------------------------------
if (!dir.exists(output_dir))    dir.create(output_dir,    recursive = TRUE)
if (!dir.exists(manuscript_dir)) dir.create(manuscript_dir, recursive = TRUE)

out1 <- file.path(output_dir,    "FigureS2_PCA_Variance.png")
out2 <- file.path(manuscript_dir, "FigureS2_PCA_Variance.png")

ggsave(out1, fig_s2, width = 12, height = 5, dpi = 300, bg = "white")
cat(sprintf("\n✓ Saved: %s\n", out1))

ggsave(out2, fig_s2, width = 12, height = 5, dpi = 300, bg = "white")
cat(sprintf("✓ Saved: %s\n", out2))

cat("\n=== FigureS2 COMPLETE ===\n")
cat("Data source: pca_explained_variance.csv (real Seurat RunPCA output)\n")
cat("No simulation used.\n")
